import { createRouter, createWebHistory } from "vue-router";

const router = createRouter({
  history: createWebHistory(),
  routes: [
    {
      path: "/",
      name: "dashboard",
      component: () => import("@/pages/DashboardPage.vue"),
      meta: { title: "Tableau de bord" },
    },
    {
      path: "/diagnostic",
      name: "diagnostic",
      component: () => import("@/pages/DiagnosticPage.vue"),
      meta: { title: "Diagnostic" },
    },
    {
      path: "/optimizations",
      name: "optimizations",
      component: () => import("@/pages/OptimizationsPage.vue"),
      meta: { title: "Optimisations" },
    },
    {
      path: "/applications",
      name: "applications",
      component: () => import("@/pages/ApplicationsPage.vue"),
      meta: { title: "Applications" },
    },
    {
      path: "/tools",
      name: "tools",
      component: () => import("@/pages/ToolsPage.vue"),
      meta: { title: "Outils Systeme" },
    },
    {
      path: "/master-install",
      name: "master-install",
      component: () => import("@/pages/MasterInstallPage.vue"),
      meta: { title: "Master Install" },
    },
    {
      path: "/portables",
      name: "portables",
      component: () => import("@/pages/PortablesPage.vue"),
      meta: { title: "Apps Portables" },
    },
    {
      path: "/os-downloads",
      name: "os-downloads",
      component: () => import("@/pages/OsDownloadsPage.vue"),
      meta: { title: "OS & USB Tools" },
    },
    {
      path: "/updates",
      name: "updates",
      component: () => import("@/pages/UpdatesPage.vue"),
      meta: { title: "Mises a jour" },
    },
    {
      path: "/drivers",
      name: "drivers",
      component: () => import("@/pages/DriversPage.vue"),
      meta: { title: "Drivers" },
    },
    { path: "/driver-scanner", redirect: "/drivers" },
    {
      path: "/backup",
      name: "backup",
      component: () => import("@/pages/BackupPage.vue"),
      meta: { title: "Sauvegarde" },
    },
    {
      path: "/uninstaller",
      name: "uninstaller",
      component: () => import("@/pages/UninstallerPage.vue"),
      meta: { title: "Désinstallateur Propre" },
    },
    {
      path: "/clone",
      name: "clone",
      component: () => import("@/pages/ClonePage.vue"),
      meta: { title: "Clonage Système" },
    },
    {
      path: "/data-recovery",
      name: "data-recovery",
      component: () => import("@/pages/DataRecoveryPage.vue"),
      meta: { title: "Récupération de Données" },
    },
    {
      path: "/scanvirus",
      name: "scanvirus",
      component: () => import("@/pages/ScanVirusPage.vue"),
      meta: { title: "Scan Antivirus" },
    },
    {
      path: "/network",
      name: "network",
      component: () => import("@/pages/NetworkPage.vue"),
      meta: { title: "Reseau" },
    },
    {
      path: "/terminal",
      name: "terminal",
      component: () => import("@/pages/TerminalPage.vue"),
      meta: { title: "Terminal" },
    },
    {
      path: "/scripts",
      name: "scripts",
      component: () => import("@/pages/ScriptsPage.vue"),
      meta: { title: "Scripts Windows" },
    },
    {
      path: "/ai-agents",
      name: "ai-agents",
      component: () => import("@/pages/AiAgentsPage.vue"),
      meta: { title: "Agent IA" },
    },
    {
      path: "/knowledge-base",
      name: "knowledge-base",
      component: () => import("@/pages/KnowledgeBasePage.vue"),
      meta: { title: "Base de Connaissances" },
    },
    {
      path: "/documentation",
      name: "documentation",
      component: () => import("@/pages/DocumentationPage.vue"),
      meta: { title: "Documentation" },
    },
    {
      path: "/logs",
      name: "logs",
      component: () => import("@/pages/LogsPage.vue"),
      meta: { title: "Logs" },
    },
    {
      path: "/theme-editor",
      name: "theme-editor",
      component: () => import("@/pages/ThemeEditorPage.vue"),
      meta: { title: "Éditeur de Thème" },
    },
    {
      path: "/settings",
      name: "settings",
      component: () => import("@/pages/SettingsPage.vue"),
      meta: { title: "Parametres" },
    },
    {
      path: "/profiles",
      name: "profiles",
      component: () => import("@/pages/ProfilesPage.vue"),
      meta: { title: "Profils de Configuration" },
    },
    {
      path: "/dependencies",
      name: "dependencies",
      component: () => import("@/pages/DependencyManagerPage.vue"),
      meta: { title: "Gestionnaire de Dépendances" },
    },
    {
      path: "/hosts-editor",
      name: "hosts-editor",
      component: () => import("@/pages/HostsEditorPage.vue"),
      meta: { title: "Éditeur Hosts" },
    },
    {
      path: "/bsod-analyzer",
      name: "bsod-analyzer",
      component: () => import("@/pages/BsodAnalyzerPage.vue"),
      meta: { title: "Analyse BSOD" },
    },
    {
      path: "/bluetooth",
      name: "bluetooth",
      component: () => import("@/pages/BluetoothPage.vue"),
      meta: { title: "Bluetooth" },
    },
    {
      path: "/benchmark",
      name: "benchmark",
      component: () => import("@/pages/BenchmarkPage.vue"),
      meta: { title: "Benchmark Système" },
    },
    {
      path: "/cleaner",
      name: "cleaner",
      component: () => import("@/pages/CleanerPage.vue"),
      meta: { title: "Nettoyeur Avancé" },
    },
    {
      path: "/perf-history",
      name: "perf-history",
      component: () => import("@/pages/PerfHistoryPage.vue"),
      meta: { title: "Historique Performances" },
    },
    {
      path: "/boot-manager",
      name: "boot-manager",
      component: () => import("@/pages/BootManagerPage.vue"),
      meta: { title: "Gestionnaire de Démarrage" },
    },
    {
      path: "/wsl",
      name: "wsl",
      component: () => import("@/pages/WslPage.vue"),
      meta: { title: "WSL" },
    },
    {
      path: "/restore-points",
      name: "restore-points",
      component: () => import("@/pages/RestorePointsPage.vue"),
      meta: { title: "Points de Restauration" },
    },
    {
      path: "/monitoring",
      name: "monitoring",
      component: () => import("@/pages/MonitoringPage.vue"),
      meta: { title: "Monitoring" },
    },
    {
      path: "/stats-reports",
      name: "stats-reports",
      component: () => import("@/pages/StatsReportsPage.vue"),
      meta: { title: "Rapports & Statistiques" },
    },
    // ═══ Nouvelles pages v26.46 ═══
    { path: "/turbo-mode", redirect: "/optimizations" },
    {
      path: "/hash-checker",
      name: "hash-checker",
      component: () => import("@/pages/HashCheckerPage.vue"),
      meta: { title: "Vérificateur de Hash" },
    },
    {
      path: "/dns-switcher",
      name: "dns-switcher",
      component: () => import("@/pages/DnsSwitcherPage.vue"),
      meta: { title: "DNS Switcher" },
    },
    {
      path: "/port-scanner",
      name: "port-scanner",
      component: () => import("@/pages/PortScannerPage.vue"),
      meta: { title: "Scanner de Ports" },
    },
    {
      path: "/disk-visualizer",
      name: "disk-visualizer",
      component: () => import("@/pages/DiskVisualizerPage.vue"),
      meta: { title: "Visualiseur Disque" },
    },
    {
      path: "/duplicate-finder",
      name: "duplicate-finder",
      component: () => import("@/pages/DuplicateFinderPage.vue"),
      meta: { title: "Détecteur de Doublons" },
    },
    {
      path: "/big-files",
      name: "big-files",
      component: () => import("@/pages/BigFilesFinderPage.vue"),
      meta: { title: "Gros Fichiers" },
    },
    {
      path: "/wifi-analyzer",
      name: "wifi-analyzer",
      component: () => import("@/pages/WifiAnalyzerPage.vue"),
      meta: { title: "Analyseur WiFi" },
    },
    {
      path: "/temperatures",
      name: "temperatures",
      component: () => import("@/pages/TemperaturesPage.vue"),
      meta: { title: "Températures" },
    },
    { path: "/snippets", redirect: "/scripts" },
    {
      path: "/docker",
      name: "docker",
      component: () => import("@/pages/DockerManagerPage.vue"),
      meta: { title: "Docker Manager" },
    },
    {
      path: "/winpe",
      name: "winpe",
      component: () => import("@/pages/WinPEModePage.vue"),
      meta: { title: "Mode WinPE" },
    },
  ],
});

export default router;
